### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by HuangCongQing** [engineerJPark/LiDARWeather#1]
Thanks for your fantastic work! When will the code be released?

**Comment by engineerJPark** [comment]
Hello, @HuangCongQing!
I'm happy and grateful for your attention to my work.

I'm quite busy these days, but I plan to release the code within the next three weeks. I will make sure to release it before the main conference for a more fluent discussion onsite. I'll tag you again when the code is available.

Thank you very much!

**Comment by engineerJPark** [comment]
Dear @HuangCongQing,

I would like to inform you that our code has been released.
I appreciate your patience.
