### ISSUE TITLE
loss error    strong_points

### ISSUE THREAD

**Issue by NiuYingchun** [engineerJPark/LiDARWeather#2]
![微信截图_20240811111829](https://github.com/user-attachments/assets/69f66777-4624-4eb1-bf3b-f2238dccd573)
Why does it only work if the argument in the red box is removed? 
LiDARWeather/mmdet3d/models/segmentors
/encoder_decoder.py     line_177

**Comment by engineerJPark** [comment]
I realized that I missed some parts that needed to be cleaned up. These sections are not necessary for the proposed method. I will edit them soon.
Thank you for your report.

Sincerely,
Junsung Park

**Comment by engineerJPark** [comment]
I have reviewed your report and made the necessary edits. Please take a look.
Thank you again for your report.

Sincerely,
Junsung Park

**Comment by NiuYingchun** [comment]
Thanks.
