### ISSUE TITLE
Question about the RandomChoice in pipeline.

### ISSUE THREAD

**Issue by fdy61** [engineerJPark/LiDARWeather#4]
In 'sj+lpd+minkunet_semantickitti.py' I have noticed the dict of RandomChoice, I am unclear about the processing logic inside RandomChoice, and I would like to check its code, but I am unable to find where the RandomChoice module is defined.

**Comment by engineerJPark** [comment]
As I remeber, RandomChoice is part of the mmcv package. I just found it and decided to use it.
