### ISSUE TITLE
Where is the .minkunet_backbone_batchnormmixer? I can't find it.

### ISSUE THREAD

**Issue by fdy61** [engineerJPark/LiDARWeather#5]

**Comment by engineerJPark** [comment]
The minkunet_backbone_batchnormmixer was abandoned during past experiments and is no longer used. You can go ahead and delete that part from the __init__ files, or you can wait for me to commit the updated code. I'm currently refactoring and debugging everything before the conference day.

**Comment by fdy61** [comment]
Thank you. 
And Another question. When I run the command of  create_data.py, there is an error of **ImportError: cannot import name 'RandomJitterPoints' from 'mmdet3d.datasets.transforms.transforms_3d'**. I have checked it and find that RandomJitterPoints module is not in it indeed.

**Comment by engineerJPark** [comment]
As mentioned in other [issue](https://github.com/engineerJPark/LiDARWeather/issues/6), I mistakenly deleted that part while refactoring the code.
You can find it in a previous commit, or if you prefer, you can wait for me to commit the updated version. I'm currently refactoring and debugging everything before the conference day.

**Comment by engineerJPark** [comment]
As I mentioned in [here](https://github.com/engineerJPark/LiDARWeather/issues/6) right before, I have fixed the issues and checked that the code runs correctly in the latest commit. Please check for this.

**Comment by fdy61** [comment]
Thank you very much!
