### ISSUE TITLE
ImportError: cannot import name 'RandomJitterPoints' from 'mmdet3d.datasets.transforms.transforms_3d'

### ISSUE THREAD

**Issue by Nuyoah0123** [engineerJPark/LiDARWeather#6]

**Comment by engineerJPark** [comment]
I apologize for the inconvenience.
I think I mistakenly deleted that part while refactoring the code.
You can find it in a previous commit, or if you prefer, you can wait for me to commit the updated version. I'm currently refactoring and debugging everything before the conference day.

**Comment by fdy61** [comment]
Previous commit seems miss it too, Have you find it?

**Comment by engineerJPark** [comment]
I have fixed the issues and checked that the code runs correctly in the latest commit. Please check for this.

**Comment by Nuyoah0123** [comment]
> I have fixed the issues and checked that the code runs correctly in the latest commit. Please check for this.

Thank you very much! Now I can run the program normally, but I have a problem. After I modified data_root = '/media/LLJ/data/semantickitti' in sj+lpd+minkunet_semantickitti.py file, it did not take effect when I ran the program. I was forced to force the modification of this code in semantickitti_dataset.py to take effect.
```
        super().__init__(
            data_root="/media/LLJ/data/SemanticKitti",
            ann_file="/home/LLJ/python_workspace/LiDARWeather/data/semantickitti/semantickitti_infos_train.pkl",
            metainfo=metainfo,
            data_prefix=data_prefix,
            pipeline=pipeline,
            modality=modality,
            ignore_index=ignore_index,
            scene_idxs=scene_idxs,
            test_mode=test_mode,
            **kwargs)
```
I wonder if there is any way to avoid this modification to adapt my file path?
Thank you again!

**Comment by engineerJPark** [comment]
As I remember, I had edited `semantickitti_dataset.py` too. Maybe this is due to the inheritance mechanism of mmengine configuration files...

As far as I know, you should override all `data_root` variables in the configuration file, but I think it is almost impossible because there are so many references to the `data_root` variable. I guess the simplest way is editing `semantickitti_dataset.py`.

**Comment by Nuyoah0123** [comment]
> As I remember, I had edited `semantickitti_dataset.py` too. Maybe this is due to the inheritance mechanism of mmengine configuration files...
> 
> As far as I know, you should override all `data_root` variables in the configuration file, but I think it is almost impossible because there are so many references to the `data_root` variable. I guess the simplest way is editing `semantickitti_dataset.py`.

I think I found the solution. Just modify `data_root` in `configs/_base_/datasets/semantickitti.py` and it will take effect.
