### ISSUE TITLE
About the domain generalization experiments

### ISSUE THREAD

**Issue by dongshuhua** [engineerJPark/LiDARWeather#9]
I want to reproduce the results of the domain generalization experiment in your paper, how can I do it?
I trained on semantickitti using "sj+lpd+minkunet_semantickitti.py" as the config profile and then tested on SemanticSTF after modifying the test_cfg, but the results were pretty bad.
Looking forward to your reply.
Best wishes!

**Comment by Frd027** [comment]
I encountered the same problem, could you tell me how you solved it?
